FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg libsndfile1 && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the application files
COPY computing_node/computing.py /app/computing.py

# Create the uploads directory
RUN mkdir -p /uploads

# Set the volume
VOLUME ["/uploads"]

# Install Python dependencies
RUN pip install --no-cache-dir pydub librosa soundfile numpy

# Expose the required ports
EXPOSE 50000 50001 50002 50003

# Set the entrypoint
CMD ["python", "/app/computing.py"]
