FROM python:3.12-slim AS backend

WORKDIR /backend

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

FROM node:18 AS frontend

WORKDIR /vue

COPY vue/package.json vue/package-lock.json ./
RUN npm install

COPY vue/ .

FROM python:3.12-slim

WORKDIR /

COPY --from=backend /backend /backend
COPY --from=frontend /vue /vue
COPY start.sh /start.sh

RUN chmod +x /start.sh

CMD ["/start.sh"]
